#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if which gtk-update-icon-cache >/dev/null 2>&1 ; then
        gtk-update-icon-cache -f -t /usr/share/icons/hicolor
    fi
fi


# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p cyswllt /usr/lib/cyswllt
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p cyswllt /usr/lib/cyswllt || true
fi

# End automatically added section

